version: '2'
services:
  ipsec:
    # IMPORTANT!!!! DO NOT CHANGE VERSION ON UPGRADE
    image: rancher/net:holder
    command: sh -c "echo Refer to router sidekick for logs; mkfifo f; exec cat f"
    network_mode: ipsec
    ports:
      - 500:500/udp
      - 4500:4500/udp
    # Force cni-driver to start first
    volumes_from:
      - cni-driver
    labels:
      io.rancher.sidekicks: router,cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.cni.link_mtu_overhead: '0'
      io.rancher.network.macsync: 'true'
      io.rancher.network.arpsync: 'true'
  router:
    cap_add:
      - NET_ADMIN
    image: rancher/net:v0.11.2
    network_mode: container:ipsec
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.ipsec: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
    sysctls:
      net.ipv4.conf.all.send_redirects: '0'
      net.ipv4.conf.default.send_redirects: '0'
      net.ipv4.conf.eth0.send_redirects: '0'
      net.ipv4.xfrm4_gc_thresh: '2147483647'
  cni-driver:
    privileged: true
    image: rancher/net:v0.11.2
    command: sh -c "touch /var/log/rancher-cni.log && exec tail ---disable-inotify -F /var/log/rancher-cni.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
        
  canal-agent:
    image: canal-agent
    network_mode: host
    depends_on:
      - canal-etcd
    volumes_from:
      - canal-driver
    labels:
      io.rancher.sidekicks: canal-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
    pid: host
    command: 
      - /opt/bin/canal-agent 
      - -debug=true 
      - -SelfStoreEndpoint 
      - ${IP}:4003 
      - -ControllerStoreEndpoint 
      - ${IP}:4003
    privileged: true
    volumes:
      - /run/canal/plugins:/run/canal/plugins
      - /var/run/netns:/var/run/netns
      - /var/run/openvswitch/:/var/run/openvswitch/
    environment:
      ETCD_ENDPOINTS: 'http://calico-etcd.calico.rancher.internal:2379'
      IP_AUTODETECT_METHOD: 'can-reach=www.google.com'

  canal-controller:
    image: canal-controller
    network_mode: host
    command:
      - /opt/bin/canal-controller
      - -SelfStoreEndpoint
      - ${IP}:4003
      - -AgentsStoreEndpoint
      - ${IP}:4003
      - -KubeServerAddr
      - ${IP}:8000
    volumes:
      - /etc/cni/net.d/:/etc/cni/net.d/
      - /etc/canal/template/:/etc/canal/template/
      - /etc/canal/AppChain/:/etc/canal/AppChain/
    environment:
      ETCD_ENDPOINTS: 'http://calico-etcd.calico.rancher.internal:2379'

  canal-driver:
    privileged: true
    image: canal_cni
    command: sh
    volumes:
      - rancher-cni-driver:/opt/cni/
    tty: true
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'canal_cni'
      io.rancher.container.dns: 'true'

  canal-etcd:
    image: quay.io/coreos/etcd:v3.0.14
    network_mode: host
    command: 
      - etcd 
      - --name 
      - center 
      - --initial-cluster 
      - center=http://${IP}:7003 
      - --initial-advertise-peer-urls 
      - http://${IP}:7003 
      - --listen-peer-urls 
      - http://${IP}:7003 
      - --listen-client-urls 
      - http://${IP}:4003 
      - --advertise-client-urls 
      - http://${IP}:4003
volumes:
  rancher-cni-driver:

