version: '2'
#0
services:
  ipsec:
    cap_add:
    - NET_ADMIN
    image: rancher/net:v0.7.5
    network_mode: ipsec
    ports:
    - 500:500/udp
    - 4500:4500/udp
    # Force cni-driver to start first
    volumes_from:
    - cni-driver
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.ipsec: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  cni-driver:
    privileged: true
    image: canal_cni
    command: sh
    volumes:
      - rancher-cni-driver:/opt/cni/
    tty: true
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'canal_cni'
      io.rancher.container.dns: 'true'
